ForceToUseNewFactionsClasses: false
MetricsOptOut: false
DontUseAsyncEvent: false
# some servers have /k as their defualt command for /factions
UseDevBanManager: false
FactionsCommand: 'f'
# Should spy mode be on by default for those who have the correct permission node.
# Accepts boolean [true/false].
spyModeOnByDefault: true
#If this is set true and your server is set online-mode:true, 
#then it allows me (james137137) to the following addiction commands,
AllowAuthorDebugAccess: true
# mutes public for the player when he/she is in a FactionChat channel (/f chat)
PublicMuteDefault: false
# reduces the chance of spam by allowing 1 message per X miliSecounds (ms)
ChatLimit: 100
# allows self command /fc mutePublic or /fc Mute (prevents public messages sent to client)
AllowPublicMuteCommand: false
#this will disabled certain commands please make sure you include the aliases 
#for example -fchatf and -ff
# they must be only contain lower case 
FactionInfoServer:
    enable: false
    port: 10137
DisabledCommands:
    - Example_fchatf
    - Example_fchatat
    - Example_fa
    - Example_fat
#Essentials support
Essentials:
    useNickName: false
    
# Set FactionChat to only be active in a certain worlds
limitworlds:
    enable: false
    worlds:
        - 'world'
        - 'factionworld'
        - 'faction_World_Nether'
    disablesendoutside: true
    disablereceiveoutside: true
    disableOtherChat: false
    
# Event Priority, only change if you know what you are doing, please refer to http://wiki.bukkit.org/Event_API_Reference#Event_Priorities
# 1 = EventPriority.LOWEST and 6 = EventPriority.MONITOR.
# any other numbers will stop the plugin
EventPriority:
    onPlayerChat: 1
    onPlayerChatLocalOption: 3
    onPlayerCommand: 1
    onPlayerJoin: 3
# Change the colors and format of each message
# you can now change leader to ** or whatever you like :-D
FactionRank:
  Leader: 'Leader'
  Officer: 'Officer'
  Member: 'Member'
  Recruit: 'Recruit'
Features:
  LocalChat:
    Enable: false
    Radius:
      Public: 50
      FactionChatChannel: -1
# prefix and suffix are for Groupmanager, PermissionsEX & bPermissions only. please PM me to request more.
FactionChatMessage:
  IncludePrefix: true
  IncludeSuffix: true
  IncludeTitle: true
  FactionChat: '&2[FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  AllyChat: '&aAlly: [FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  TruceChat: '&aTruce: [FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  AllyTruceChat: '&aALLY-TRUCE: [FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  OfficerChat: '&eOfficerChat: [FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  LeaderChat: '&eLeaderChat: [FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  EnemyChat: '&cEnemy: [FACTION] &f[FACTIONRANK] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  OtherFactionChatTo: '&5[@:OTHERFACTION] &f[FACTION] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  OtherFactionChatFrom: '&5[From:FACTION] &f[{OTHERFACTION}] TITLEPREFIX PLAYER SUFFIX: MESSAGE'
  SpyChat: '&2Spy:&r MESSAGE'
OtherChatMessage:
  ModChat: '&b[Mod-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
  AdminChat: '&4[Admin-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
  UAChat: '&5[UA-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
  JrModChat: '&b[JrMod-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
  SrModChat: '&b[SrMod-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
  JrAdminChat: '&4[JrAdmin-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
  VIPChat: '&e[VIP-Chat] &fPREFIX PLAYER SUFFIX: &aMESSAGE'
#Enable/disable any chat (except public)
FactionChatEnable: true
AllyChatEnable: true
TruceChatEnable: true
AllyTruceChatEnable: true
LeaderChatEnable: true
OfficerChatEnable: true
EnemyChatEnable: true
OtherChatEnable: true
ModChatEnable: true
AdminChatEnable: true
JrModChatEnable: true
SrModChatEnable: true
JrAdminChatEnable: true
UAChatEnable: true
VIPChatEnable: true
# What language should the messages be in. Accepts 'english', or 'other' only.
MessageLanguage: english
# These can be modified to your liking.
message:
  english:
    NotInFaction: You are not member of any faction
    IncorectChatModeSwitch: 'Error: please use /fc to switch chat mode or'
    SpyModeOn: Spy mode is now on
    SpyModeOff: Spy mode is now off
    NewChatMode: 'Your chat mode has been changed to: '
    FchatoMissType: 'Error: Please use /fco factionname message.'
    FchatoNoOneOnline: 'Error: either no faction member is online or incorrect faction
      name'
    PublicMuteChatOn: 'Public chat is now muted for you'
    PublicMuteChatOff: 'Public chat is no longer muted for you'
    AllyMuteChatOn: 'Ally chat is now muted for you'
    AllyMuteChatOff: 'Ally chat is no longer muted for you'
    
  other:
    NotInFaction: You are not member of any faction
    IncorectChatModeSwitch: 'Error: please use /fc to switch chat mode or'
    SpyModeOn: Spy mode is now on
    SpyModeOff: Spy mode is now off
    NewChatMode: 'Your chat mode has been changed to: '
    FchatoMissType: 'Error: Please use /fco factionname message.'
    FchatoNoOneOnline: 'Error: either no faction member is online or incorrect faction
      name'
    PublicMuteChatOn: 'Public chat is now muted for you'
    PublicMuteChatOff: 'Public chat is no longer muted for you'
   
 #name and colour customization when player changes channel e.g. /f c ally
  ChatModeChange:
    FactionChat: '&2Faction'
    AllyChat: '&aAlly'
    TruceChat: '&aTruce'
    AllyTruceChat: '&aAlly-Truce'
    EnemyChat: '&cEnemy'
    LeaderChat: '&eLeader'
    OfficerChat: '&eOfficer'
    PublicChat: 'PUBLIC'
